---
- hosts: tag_Name_JAY_nginx
- name: nginx assignment
  import_playbook: ../static-assignments/nginx.yml

- hosts: tag_Name_JAY_tooling
- name: tooling assignment
  import_playbook: ../static-assignments/tooling.yml

- hosts: tag_Name_JAY_wordpress
- name: wordpress assignment
  import_playbook: ../static-assignments/wordpress.yml
# - hosts: tag_Name_JAY_jenkins
# - name: jenkins assignment
#   import_playbook: ../static-assignments/jenkins.yml

# - hosts: tag_Name_JAY_artifactory
# - name: artifactory assignment
#   import_playbook: ../static-assignments/jfrog.yml

#- hosts: tag_Name_JAY_sonarqube
#  user: ubuntu
#- name: sonarqube assignment
#  import_playbook: ../static-assignments/sonar.yml
